/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import kps.server.KPSServer;
import kps.client.Client;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        switch (args.length) {
	case 2: KPSServer.main(args); break;
        case 0: Client.main(args); break;
	default: System.out.println("Goodbye World"); break;
	}
	
    }
}
